DROP TABLE IF EXISTS pujjr_credit_crime_info ;

CREATE TABLE pujjr_credit_crime_info (
  id BIGINT (20) NOT NULL AUTO_INCREMENT,
  case_source VARCHAR (50) COLLATE utf8_bin DEFAULT NULL,
  case_time VARCHAR (50) COLLATE utf8_bin DEFAULT NULL,
  case_type VARCHAR (50) COLLATE utf8_bin DEFAULT NULL,
  credit_record_Id BIGINT (20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FKCF28DC2F487C768A (credit_record_Id),
  CONSTRAINT FKCF28DC2F487C768A FOREIGN KEY (credit_record_Id) REFERENCES pujjr_credit_query_result (record_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin ;

DROP TABLE IF EXISTS pujjr_credit_execution ;

CREATE TABLE pujjr_credit_execution (
  id BIGINT (20) NOT NULL AUTO_INCREMENT,
  ex_bad_base VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_basecompany VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_breaktime VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_casenum VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_concretesituation VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_court VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_datatype VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_money VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_performance VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_bad_time VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_execut_basic VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_execut_basiccourt VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_execut_casenum VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_execut_court VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_execut_datatype VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_execut_money VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_execut_statute VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  ex_execut_time VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  execution_type VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  credit_record_Id BIGINT (20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FKB27E3844487C768A (credit_record_Id),
  CONSTRAINT FKB27E3844487C768A FOREIGN KEY (credit_record_Id) REFERENCES pujjr_credit_query_result (record_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin ;

DROP TABLE IF EXISTS pujjr_credit_per_invest ;

CREATE TABLE pujjr_credit_per_invest (
  id BIGINT (20) NOT NULL AUTO_INCREMENT,
  entname VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  entstatus VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  enttype VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  fundedratio VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  perinvest_type VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  regcap VARCHAR (100) COLLATE utf8_bin DEFAULT NULL,
  credit_record_Id BIGINT (20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FK7969D9AB487C768A (credit_record_Id),
  CONSTRAINT FK7969D9AB487C768A FOREIGN KEY (credit_record_Id) REFERENCES pujjr_credit_query_result (record_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin ;

DROP TABLE IF EXISTS pujjr_credit_rskdoo;

CREATE TABLE pujjr_credit_rskdoo (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  data_build_time VARCHAR(24) COLLATE utf8_bin DEFAULT NULL,
  rsk_mark VARCHAR(8) COLLATE utf8_bin DEFAULT NULL,
  rsk_score VARCHAR(8) COLLATE utf8_bin DEFAULT NULL,
  source_id VARCHAR(2) COLLATE utf8_bin DEFAULT NULL,
  credit_record_Id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FK9440F10E487C768A (credit_record_Id),
  CONSTRAINT FK9440F10E487C768A FOREIGN KEY (credit_record_Id) REFERENCES pujjr_credit_query_result (record_id)
) ENGINE=INNODB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS pujjr_credit_query_result ;

CREATE TABLE pujjr_credit_query_result (
  record_id BIGINT (20) NOT NULL AUTO_INCREMENT,
  br_m12_cell_loan_num INT (11) DEFAULT NULL,
  br_m12_id_loan_num INT (11) DEFAULT NULL,
  br_m1_cell_loan_num INT (11) DEFAULT NULL,
  br_m1_id_loan_num INT (11) DEFAULT NULL,
  br_m3_cell_loan_num INT (11) DEFAULT NULL,
  br_m3_id_loan_num INT (11) DEFAULT NULL,
  br_m6_cell_loan_num INT (11) DEFAULT NULL,
  br_m6_id_loan_num INT (11) DEFAULT NULL,
  chk_driver_no VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_name VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_status VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  credit_id VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  data_build_time VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  is_mach_fraud VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_bl_makt VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_owner_mobile VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  owner_mobile_status VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  qh_m12_id_loan_num INT (11) DEFAULT NULL,
  qh_m1_id_loan_num INT (11) DEFAULT NULL,
  qh_m3_id_loan_num INT (11) DEFAULT NULL,
  qh_m6_id_loan_num INT (11) DEFAULT NULL,
  rsk_mark VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  rsk_score VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  source_id VARCHAR (2) COLLATE utf8_bin DEFAULT NULL,
  use_time_score VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  credit_request_Id BIGINT (20) DEFAULT NULL,
  PRIMARY KEY (record_id),
  KEY FK13726EC81E368EE2 (credit_request_Id),
  CONSTRAINT FK13726EC81E368EE2 FOREIGN KEY (credit_request_Id) REFERENCES pujjr_credit_request (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin ;

DROP TABLE IF EXISTS pujjr_credit_request ;

CREATE TABLE pujjr_credit_request (
  id BIGINT (20) NOT NULL AUTO_INCREMENT,
  credit_id VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  criminal_record INT (11) DEFAULT NULL,
  entity_auth_code VARCHAR (32) COLLATE utf8_bin NOT NULL,
  entity_auth_date VARCHAR (32) COLLATE utf8_bin NOT NULL,
  err_msg VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  id_no VARCHAR (24) COLLATE utf8_bin NOT NULL,
  id_type VARCHAR (8) COLLATE utf8_bin NOT NULL,
  invest_info INT (11) DEFAULT NULL,
  mobile_no VARCHAR (24) COLLATE utf8_bin NOT NULL,
  NAME VARCHAR (255) COLLATE utf8_bin NOT NULL,
  oss_key VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  reason_code VARCHAR (8) COLLATE utf8_bin NOT NULL,
  request_date DATETIME NOT NULL,
  request_user_id VARCHAR (24) COLLATE utf8_bin NOT NULL,
  risk_level INT (11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin ;

ALTER TABLE pujjr_credit_request ADD UNIQUE(id_no,mobile_no,NAME);

DROP TABLE IF EXISTS pujjr_hundred_credit_request ;

CREATE TABLE pujjr_hundred_credit_request (
  request_id BIGINT (20) NOT NULL AUTO_INCREMENT,
  ip VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  mac VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  af_swift_number VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  age INT (11) DEFAULT NULL,
  api_type VARCHAR (255) COLLATE utf8_bin NOT NULL,
  app_visit_num INT (11) DEFAULT NULL,
  apply_addr VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  apply_money VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  apply_product VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  apply_source INT (11) DEFAULT NULL,
  apply_time VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  apply_type VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  bank_id VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  bank_running_att_num INT (11) DEFAULT NULL,
  biz_addr VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  biz_industry INT (11) DEFAULT NULL,
  biz_orgcode VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  biz_positon INT (11) DEFAULT NULL,
  biz_regnum VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  biz_taxnum VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  biz_type INT (11) DEFAULT NULL,
  biz_workfor VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  carnum VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  cell VARCHAR (255) COLLATE utf8_bin NOT NULL,
  daily_photo VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  device_id VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  device_id2 VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  device_id3 VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  device_type VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  device_type2 VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  device_type3 VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  downstream_count VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  edu_att_num INT (11) DEFAULT NULL,
  educationallevel INT (11) DEFAULT NULL,
  enginenum VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  EVENT VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  gid VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  home_addr VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  house_type INT (11) DEFAULT NULL,
  id VARCHAR (255) COLLATE utf8_bin NOT NULL,
  id_photo VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  imei VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  imsi VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  income DOUBLE DEFAULT NULL,
  das_index VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  key_no VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  latitude VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  linkman_cell VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  linkman_name VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  linkman_rela VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  loan_reason VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  longitude VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  mail VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  marriage INT (11) DEFAULT NULL,
  meal VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  mobile_type VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  NAME VARCHAR (255) COLLATE utf8_bin NOT NULL,
  oth_addr VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  per_addr VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  postalcode VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  refund_periods INT (11) DEFAULT NULL,
  request_date DATETIME NOT NULL,
  request_user_id VARCHAR (255) COLLATE utf8_bin NOT NULL,
  search_key VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  sex VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  sub_org_name VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  tel_biz VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  tel_home VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  tokenid VARCHAR (255) COLLATE utf8_bin NOT NULL,
  upstream_count VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  user_id VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  user_name VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  user_nickname VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  vinnum VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (request_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin ;

DROP TABLE IF EXISTS pujjr_qian_hai_result ;

CREATE TABLE pujjr_qian_hai_result (
  record_id BIGINT (20) NOT NULL AUTO_INCREMENT,
  address_type VARCHAR (256) COLLATE utf8_bin DEFAULT NULL,
  amount VARCHAR (16) COLLATE utf8_bin DEFAULT NULL,
  appear1th_date VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  appear_last_date VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  batch_no VARCHAR (24) COLLATE utf8_bin NOT NULL,
  busi_date VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  car_chk_result VARCHAR (1) COLLATE utf8_bin DEFAULT NULL,
  car_factory_inc VARCHAR (128) COLLATE utf8_bin DEFAULT NULL,
  car_price VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  car_type_inc VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  chk_archives_no VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_birthday VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_birthday4 VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_birthday6 VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_driver_no VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_first_licensing_date VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_first_licensing_date4 VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_first_licensing_date6 VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_name VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_nationality VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_quasi_driving_vehicle VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_result VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_status VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_valid_date_end VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_valid_date_end4 VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_valid_date_end6 VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_valid_date_start VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_valid_date_start4 VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  chk_valid_date_start6 VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  company_sim_deg VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  data_build_time VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  data_date VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  data_status VARCHAR (2) COLLATE utf8_bin DEFAULT NULL,
  drv_status_qry_id VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  er_code VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  er_msg VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  error_info VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  graduate_major VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  graduate_school VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  graduate_year VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  house_chk_result VARCHAR (1) COLLATE utf8_bin DEFAULT NULL,
  house_data_date VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  i_rsk_desc VARCHAR (1024) COLLATE utf8_bin DEFAULT NULL,
  i_update_date VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  id_no VARCHAR (64) COLLATE utf8_bin NOT NULL,
  id_type VARCHAR (2) COLLATE utf8_bin NOT NULL,
  industry VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  ip VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  is_asyned VARCHAR (1) COLLATE utf8_bin DEFAULT NULL,
  is_exist_rel VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_highest_edu_bkg VARCHAR (1) COLLATE utf8_bin DEFAULT NULL,
  is_mach_cra_call VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_mach_empty VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_mach_fraud VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machszno VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_mach_small_no VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machyzmobile VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_bl_makt VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_blacklist VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_crawler VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machddns VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_force VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_mail_serv VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_org VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_proxy VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machdvpn VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_machd_web_serv VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_owner_mobile VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_owner_mobileii VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_real_company VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_real_identity VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  is_valid_address VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  m_rsk_desc VARCHAR (1024) COLLATE utf8_bin DEFAULT NULL,
  m_update_date VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  mobile_no VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  NAME VARCHAR (128) COLLATE utf8_bin NOT NULL,
  owner_mobile_status VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  owner_mobile_statusii VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  photo_cmp_result VARCHAR (255) COLLATE utf8_bin DEFAULT NULL,
  photo_sim_deg VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  query_id VARCHAR (64) COLLATE utf8_bin DEFAULT NULL,
  query_product_type VARCHAR (64) COLLATE utf8_bin NOT NULL,
  reason_code VARCHAR (2) COLLATE utf8_bin DEFAULT NULL,
  rel_level VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  rsk_mark VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  rsk_score VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  seois_machdseo VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  seq_no VARCHAR (24) COLLATE utf8_bin NOT NULL,
  source_id VARCHAR (2) COLLATE utf8_bin DEFAULT NULL,
  submit_trans_no VARCHAR (24) COLLATE utf8_bin DEFAULT NULL,
  trans_no VARCHAR (24) COLLATE utf8_bin NOT NULL,
  use_time_score VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  use_time_scoreii VARCHAR (8) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (record_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin ;

